export const commonMessages = {
  en: {
    member: "Membership", staff: "Store desk", admin: "Management", portal: "Workspaces", language: "Language", signOut: "Sign out", open: "Open", enter: "Continue", chooseWorkspace: "Your workspace", singapore: "Singapore", close: "Close", refresh: "Refresh", loading: "Loading…", saving: "Saving…", retry: "Try again", networkError: "Connection interrupted. Try again.", unknownError: "Unable to complete this action. Try again.", success: "Changes saved", sessionExpired: "Your session has ended. Sign in again.", unavailable: "Sign-in unavailable", memberAccess: "Member account", staffAccess: "Store account", adminAccess: "Head office account",
    errors: {
      GIFT_IN_USE: "This reward has redemptions awaiting handover. Complete or cancel them before deleting it.", STORE_IN_USE: "This store has redemptions awaiting handover. Complete or cancel them before deleting it.",
      STORE_INACTIVE: "This store is unavailable.", INVALID_REDEMPTION_STATE: "This redemption has already changed. Refresh and try again.", REFUND_EXCEEDS_AMOUNT: "The amount exceeds the refundable balance.", INVALID_RULES: "Check the membership rules.", INVALID_MEMBER_CODE: "This member code is invalid.", UNAUTHORIZED: "Your session has ended. Sign in again.", FORBIDDEN: "You do not have permission for this action.", INVALID_INPUT: "Check the details and try again.", MEMBER_NOT_FOUND: "Member not found.", MEMBER_SUSPENDED: "This membership is suspended.", INSUFFICIENT_POINTS: "Not enough points for this reward.", INSUFFICIENT_STOCK: "This reward is out of stock at the selected store.", MONTHLY_LIMIT: "The monthly redemption allowance has been used.", DUPLICATE_RECEIPT: "This receipt has already been recorded.", IDEMPOTENCY_CONFLICT: "This request was already used for different details.", INVALID_STATE: "This record has already changed. Refresh and try again.", EXCESS_REFUND: "The amount exceeds the refundable balance.", GIFT_UNAVAILABLE: "This reward is no longer available.", NOT_FOUND: "This record could not be found.", DEMO_DISABLED: "Sign-in unavailable.", CONFLICT: "This record has changed. Refresh and try again.", INVALID_ORIGIN: "This request could not be verified.", INTERNAL_ERROR: "Unable to complete this action. Try again."
    }
  },
  "zh-CN": {
    member: "会员中心", staff: "门店工作台", admin: "总部管理", portal: "工作空间", language: "语言", signOut: "退出登录", open: "进入", enter: "继续", chooseWorkspace: "选择工作空间", singapore: "新加坡", close: "关闭", refresh: "刷新", loading: "加载中…", saving: "保存中…", retry: "重试", networkError: "连接中断，请重试。", unknownError: "操作未完成，请重试。", success: "已保存", sessionExpired: "登录已失效，请重新登录。", unavailable: "暂时无法登录", memberAccess: "会员账户", staffAccess: "门店账户", adminAccess: "总部账户",
    errors: {
      GIFT_IN_USE: "此礼品仍有待交付的兑换，请先完成交付或取消兑换后再删除。", STORE_IN_USE: "此门店仍有待交付的兑换，请先完成交付或取消兑换后再删除。",
      STORE_INACTIVE: "该门店暂不可用。", INVALID_REDEMPTION_STATE: "兑换状态已更新，请刷新后重试。", REFUND_EXCEEDS_AMOUNT: "金额超出剩余可退金额。", INVALID_RULES: "请检查会员规则。", INVALID_MEMBER_CODE: "会员码无效。", UNAUTHORIZED: "登录已失效，请重新登录。", FORBIDDEN: "你没有执行此操作的权限。", INVALID_INPUT: "请检查输入内容后重试。", MEMBER_NOT_FOUND: "未找到会员。", MEMBER_SUSPENDED: "该会员账户已停用。", INSUFFICIENT_POINTS: "积分不足，无法兑换。", INSUFFICIENT_STOCK: "所选门店的礼品库存不足。", MONTHLY_LIMIT: "本月兑换额度已用完。", DUPLICATE_RECEIPT: "该收据已登记。", IDEMPOTENCY_CONFLICT: "该请求已用于其他内容。", INVALID_STATE: "记录状态已更新，请刷新后重试。", EXCESS_REFUND: "金额超出剩余可退金额。", GIFT_UNAVAILABLE: "该礼品已下架。", NOT_FOUND: "未找到该记录。", DEMO_DISABLED: "暂时无法登录。", CONFLICT: "记录已更新，请刷新后重试。", INVALID_ORIGIN: "无法验证该请求。", INTERNAL_ERROR: "操作未完成，请重试。"
    }
  }
};
